### ISSUE TITLE
Script is not visible in github 

### ISSUE THREAD

**Issue by marloesmul** [wateraccounting/WaPORMOOC#2]
Error message in figure
![Capture](https://github.com/wateraccounting/WaPORMOOC/assets/53043633/ff82ca5f-a81f-4594-b0f1-b60662fcc0ae)

**Comment by trngbich** [comment]
[https://github.com/orgs/community/discussions/124651](https://github.com/orgs/community/discussions/124651) it's a global error happening to all Github users

**Comment by marloesmul** [comment]
seems to be working again
